### PR TITLE
HOMS MR1L3 States

### PR DESCRIPTION
**Pull request by nrwslac**
Set MR1L3 Y axis states(Non PMPS): SiC, W and X axis states: In, Out. Added a new pydm screen: mirrorScreen.ui

### CODE REVIEW

**Comment by ZLLentz** [comment]
Screenshots of the ui file for reference (default size, on a 2K monitor):
image
(minimum size):
image

"Advanced Motor" button opens up a typhos screen:
image

**Comment by ZLLentz** [comment]
Everything on the ui looks good to me except the limit indicators are unlabeled and extremely confusing

**Comment by nrwslac** [comment]
> > I thought the limits were intuitive enough without a label, but open to adding labels.
> 
> I think my brain saw three numbers right next to eachother with only a "cur" label and assumed I was looking at X/Y or something rather than HLM LLM.
> 
> The visual signal that usually clues me in to something being an HLM or an LLM is the inclusion of the light-up circle that glows when you hit the limit
> 
> It's probably optimal to deploy as-is and wait for user feedback before revising.
> 
> One quick addition would be to include the Y/X mm float positions next to the current state name so that the user knows when the motors are moving properly after clicking the state button, they could watch those numbers go up/down

There's a Green moving Box that pops up when either of the states is moving into position; used this is indicator of motion instead of the Y/X pos approach.

**Comment by ZLLentz** [comment]
Oh, okay, I don't see that at all in my screenshot. Is it transparent when not moving?
I still know from past experiences that scientists like to watch the numbers change (this is a common complaint about the current ppm typhos screen, can't see the raw number in the same view as the states box...)

**Pull request merged**
